//! Scaffold for the generated SDK and Terraform provider artifacts.
//!
//! This module renders the per-language artifact text into a stable,
//! byte-stable buffer. CI checks the rendered bytes against the
//! committed copies in `iac/scaffold/`.

use openpanel_domain::iac::contract::ApiContract;
use openpanel_domain::iac::provider::ResourceKind;

/// Render a minimal Rust client stub that lists the SDK surfaces
/// produced from `contract`. The text is deliberately small and
/// stable so the drift check is meaningful.
pub fn render_rust_stub(contract: &ApiContract) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by `openpanel iac generate`.\n");
    out.push_str("// DO NOT EDIT — regenerate from openapi.rs.\n");
    out.push_str(&format!(
        "// OpenAPI version: {}\n",
        contract.openapi_version
    ));
    out.push_str("\n/// Typed SDK client.\n");
    out.push_str("pub struct Client {\n    pub token: String,\n}\n\n");
    out.push_str("impl Client {\n");
    out.push_str("    pub fn new(token: impl Into<String>) -> Self { Self { token: token.into() } }\n");
    let mut ops: Vec<_> = contract.operations.iter().collect();
    ops.sort_by(|a, b| a.id.as_str().cmp(b.id.as_str()));
    for op in ops {
        out.push_str(&format!(
            "    /// OpenAPI operation `{}`.\n    pub async fn {}(&self) -> Result<(), reqwest::Result<()>> {{ Ok(()) }}\n",
            op.id.as_str(),
            camel(&op.id.as_str()),
        ));
    }
    out.push_str("}\n");
    out
}

/// Render a minimal Go module stub.
pub fn render_go_stub(contract: &ApiContract) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by `openpanel iac generate`.\n");
    out.push_str("// DO NOT EDIT — regenerate from openapi.rs.\n");
    out.push_str("package openpanel\n\n");
    out.push_str(&format!("// OpenAPI version: {}\n", contract.openapi_version));
    out.push_str("type Client struct{ Token string }\n\n");
    out.push_str("func NewClient(token string) *Client { return &Client{Token: token} }\n");
    let mut ops: Vec<_> = contract.operations.iter().collect();
    ops.sort_by(|a, b| a.id.as_str().cmp(b.id.as_str()));
    for op in ops {
        out.push_str(&format!(
            "func (c *Client) {}(ctx context.Context) error {{ return nil }}\n",
            pascal(&op.id.as_str()),
        ));
    }
    out
}

/// Render a minimal TypeScript package stub.
pub fn render_typescript_stub(contract: &ApiContract) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by `openpanel iac generate`.\n");
    out.push_str("// DO NOT EDIT — regenerate from openapi.rs.\n");
    out.push_str(&format!(
        "// OpenAPI version: {}\n",
        contract.openapi_version
    ));
    out.push_str("export class Client {\n  constructor(public token: string) {}\n");
    let mut ops: Vec<_> = contract.operations.iter().collect();
    ops.sort_by(|a, b| a.id.as_str().cmp(b.id.as_str()));
    for op in ops {
        out.push_str(&format!(
            "  async {}(req: Request): Promise<Response> {{ return fetch('', {{}}) }}\n",
            camel(&op.id.as_str()),
        ));
    }
    out.push_str("}\n");
    out
}

/// Render a minimal Terraform provider main stub listing the
/// supported resources.
pub fn render_provider_stub(contract: &ApiContract) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by `openpanel iac generate`.\n");
    out.push_str("// DO NOT EDIT — regenerate from openapi.rs.\n");
    out.push_str("package main\n\n");
    out.push_str("import (\n");
    out.push_str("    \"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema\"\n");
    out.push_str("    \"github.com/hashicorp/terraform-plugin-sdk/v2/plugin\"\n");
    out.push_str(")\n\n");
    out.push_str(&format!(
        "// OpenAPI version: {}\n",
        contract.openapi_version
    ));
    let resources: Vec<ResourceKind> = contract
        .resource_endpoints
        .iter()
        .map(|r| r.kind)
        .collect();
    out.push_str("func Provider() *schema.Provider {\n    return &schema.Provider{\n");
    out.push_str("        ResourcesMap: map[string]*schema.Resource{\n");
    for r in resources {
        out.push_str(&format!(
            "            \"{}\": {{ /* resource spec */ }},\n",
            r.as_str()
        ));
    }
    out.push_str("        },\n    }\n}\n\n");
    out.push_str("func main() { plugin.Serve(Provider().GRPCProviderPlugin) }\n");
    out
}

fn camel(id: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in id.chars() {
        if ch == '.' || ch == '_' || ch == '-' {
            upper = true;
            continue;
        }
        if upper {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn pascal(id: &str) -> String {
    camel(id)
}

#[cfg(test)]
mod tests {
    use super::*;
    use openpanel_domain::iac::contract::{Operation, OperationId};
    use openpanel_domain::iac::provider::ResourceKind;

    fn contract() -> ApiContract {
        ApiContract {
            openapi_version: "1.0.0".into(),
            operations: vec![
                Operation {
                    id: OperationId::new("sites.list"),
                    method: "get".into(),
                    path: "/sites".into(),
                    family: "sites".into(),
                },
                Operation {
                    id: OperationId::new("sites.create"),
                    method: "post".into(),
                    path: "/sites".into(),
                    family: "sites".into(),
                },
            ],
            resource_endpoints: vec![openpanel_domain::iac::contract::ResourceEndpoint {
                kind: ResourceKind::Site,
                create_op: OperationId::new("sites.create"),
                read_op: OperationId::new("sites.read"),
                delete_op: OperationId::new("sites.delete"),
            }],
        }
    }

    #[test]
    fn rust_stub_lists_operations_sorted() {
        let stub = render_rust_stub(&contract());
        assert!(stub.contains("SitesList"));
        assert!(stub.contains("SitesCreate"));
        assert!(stub.contains("OpenAPI version: 1.0.0"));
    }

    #[test]
    fn provider_stub_lists_backed_resources() {
        let stub = render_provider_stub(&contract());
        assert!(stub.contains("openpanel_site"));
        assert!(!stub.contains("openpanel_user"));
    }

    #[test]
    fn byte_stability_for_unchanged_contract() {
        let a = render_rust_stub(&contract());
        let b = render_rust_stub(&contract());
        assert_eq!(a, b);
    }
}