//! Embedded recovery seed for the Software Center aggregator.
//!
//! This manifest is the *last-resort* fallback used only on first boot
//! when no remote manifest has ever been activated and the network is
//! unreachable. The remote signed manifest is the source of truth; this
//! seed exists to keep the page useful when offline.
//!
//! The set is deliberately a starting point covering the most common
//! hosting stack: web servers, PHP runtimes, databases, caches, operator
//! tools, and one-click applications. Every entry has at least one tag,
//! a license, a developer, a homepage, a short and long description, and
//! at least one version. Web entries have a pinned `ArtifactPin` with a
//! published digest (or a documented placeholder when the upstream does
//! not publish SHA-256 — those entries will fail the live digest check
//! and are clearly marked).
//!
//! The seed is build-time developer data; `.expect` on developer-authored
//! values is intentional so that any future schema drift fails loudly at
//! compile or test time rather than silently shipping a half-built
//! manifest.
#![allow(clippy::expect_used, clippy::too_many_arguments, missing_docs)]

use openpanel_domain::software_center::{
    ArtifactPin, CatalogEntryRecipe, CatalogManifest, Category, EntryKind, Homepage, License,
    SupportedPlatform, Tag, VersionSpec,
};

/// Maximum disk delta estimate for a typical install. Used as a fallback
/// when the recipe does not declare one.
const fn mib(mebibytes: u64) -> u64 {
    mebibytes * 1024 * 1024
}

fn artifact(url: &str, sha256: &str, archive_root: &str, sha1: Option<&str>) -> ArtifactPin {
    ArtifactPin {
        url: Homepage::new(url).expect("seed artifact url must validate"),
        sha256: sha256.to_owned(),
        archive_root: archive_root.to_owned(),
        archive_type: "tar.gz".to_owned(),
        sha1: sha1.map(str::to_owned),
    }
}

fn file_artifact(url: &str, sha256: &str, filename: &str) -> ArtifactPin {
    ArtifactPin {
        url: Homepage::new(url).expect("seed artifact url must validate"),
        sha256: sha256.to_owned(),
        archive_root: filename.to_owned(),
        archive_type: "file".to_owned(),
        sha1: None,
    }
}

fn version(
    version: &str,
    size_bytes: u64,
    artifact: Option<ArtifactPin>,
    packages: Vec<&str>,
    supports_php: Vec<&str>,
    released_at: Option<&str>,
) -> VersionSpec {
    VersionSpec {
        version: version.to_owned(),
        size_bytes,
        changelog_url: None,
        artifact,
        packages: packages.into_iter().map(str::to_owned).collect(),
        supports_php: supports_php.into_iter().map(str::to_owned).collect(),
        released_at: released_at.map(str::to_owned),
    }
}

/// Build the default platform list for a seed entry. Most entries
/// support every host OpenPanel recognizes. Specific entries can
/// override by passing a non-empty `platforms` list.
fn default_platforms() -> Vec<SupportedPlatform> {
    [
        "ubuntu 22.04 x86_64",
        "ubuntu 22.04 aarch64",
        "ubuntu 24.04 x86_64",
        "ubuntu 24.04 aarch64",
        "debian 12 x86_64",
        "debian 12 aarch64",
    ]
    .iter()
    .filter_map(|value| {
        let mut parts = value.split_whitespace();
        let distribution = parts.next()?;
        let release = parts.next()?;
        let architecture = parts.next()?;
        SupportedPlatform::new(distribution, release, architecture).ok()
    })
    .collect()
}

fn entry(
    id: &str,
    name: &str,
    description: &str,
    long: &str,
    category: Category,
    kind: EntryKind,
    tags: &[&str],
    license: &str,
    developer: &str,
    homepage: &str,
    versions: Vec<VersionSpec>,
    dependencies: Vec<&str>,
    conflicts: Vec<&str>,
    icon: Option<&str>,
) -> CatalogEntryRecipe {
    entry_with_platforms(
        id,
        name,
        description,
        long,
        category,
        kind,
        tags,
        license,
        developer,
        homepage,
        versions,
        dependencies,
        conflicts,
        icon,
        default_platforms(),
    )
}

fn entry_with_platforms(
    id: &str,
    name: &str,
    description: &str,
    long: &str,
    category: Category,
    kind: EntryKind,
    tags: &[&str],
    license: &str,
    developer: &str,
    homepage: &str,
    versions: Vec<VersionSpec>,
    dependencies: Vec<&str>,
    conflicts: Vec<&str>,
    icon: Option<&str>,
    platforms: Vec<SupportedPlatform>,
) -> CatalogEntryRecipe {
    CatalogEntryRecipe {
        id: id.to_owned(),
        name: name.to_owned(),
        description: description.to_owned(),
        long_description: long.to_owned(),
        category,
        kind,
        tags: tags
            .iter()
            .map(|value| Tag::new(value).expect("seed tag must validate"))
            .collect(),
        license: License::new(license).expect("seed license must validate"),
        developer: developer.to_owned(),
        homepage: Homepage::new(homepage).expect("seed homepage must validate"),
        versions,
        platforms,
        dependencies: dependencies.into_iter().map(str::to_owned).collect(),
        conflicts: conflicts.into_iter().map(str::to_owned).collect(),
        icon: icon.map(str::to_owned),
        screenshot: None,
    }
}

pub fn entries() -> Vec<CatalogEntryRecipe> {
    vec![
        // =============== Web servers ===============
        entry(
            "nginx",
            "Nginx",
            "High-performance HTTP and reverse proxy server.",
            "Nginx is the panel's default web server. The recipe installs the distro package, validates the configuration with `nginx -t`, and registers the service with the allowlisted system-services layer.",
            Category::WebServer,
            EntryKind::System,
            &["web", "http", "proxy"],
            "BSD-2-Clause",
            "F5 Networks",
            "https://nginx.org",
            vec![version(
                "1.24.0",
                mib(14),
                None,
                vec!["nginx"],
                Vec::new(),
                Some("2024-04-16"),
            )],
            Vec::new(),
            vec!["apache", "openlitespeed"],
            Some("nginx"),
        ),
        entry(
            "apache",
            "Apache HTTP Server",
            "Mature, modular HTTP server with the broadest ecosystem.",
            "Apache is the historical default web server. The recipe installs the distro package, enables the rewrite and SSL modules, and registers the service.",
            Category::WebServer,
            EntryKind::System,
            &["web", "http"],
            "Apache-2.0",
            "Apache Software Foundation",
            "https://httpd.apache.org",
            vec![version(
                "2.4.59",
                mib(22),
                None,
                vec!["apache2"],
                Vec::new(),
                Some("2024-04-04"),
            )],
            Vec::new(),
            vec!["nginx", "openlitespeed"],
            Some("apache"),
        ),
        entry(
            "openlitespeed",
            "OpenLiteSpeed",
            "Event-driven high-performance web server with a built-in administration console.",
            "OpenLiteSpeed is the open-source build of LiteSpeed. The recipe installs the official package and registers the service unit. It is mutually exclusive with Nginx and Apache on port 80.",
            Category::WebServer,
            EntryKind::System,
            &["web", "http", "event-driven"],
            "GPL-3.0-only",
            "LiteSpeed Technologies",
            "https://openlitespeed.org",
            vec![version(
                "1.8.1",
                mib(40),
                None,
                vec!["openlitespeed", "lsphp"],
                Vec::new(),
                Some("2024-05-07"),
            )],
            Vec::new(),
            vec!["nginx", "apache"],
            Some("openlitespeed"),
        ),
        // =============== PHP runtimes ===============
        entry(
            "php-7.4",
            "PHP 7.4",
            "PHP-FPM 7.4 runtime with the common CMS extensions.",
            "PHP 7.4 is the last release of the 7.x line. Maintained for legacy applications; new projects should use 8.1 or later.",
            Category::Runtime,
            EntryKind::System,
            &["php", "runtime", "fpm"],
            "PHP-3.01",
            "PHP Group",
            "https://www.php.net",
            vec![version(
                "7.4.33",
                mib(82),
                None,
                vec![
                    "php7.4-fpm",
                    "php7.4-cli",
                    "php7.4-curl",
                    "php7.4-gd",
                    "php7.4-intl",
                    "php7.4-mbstring",
                    "php7.4-mysql",
                    "php7.4-xml",
                    "php7.4-zip",
                ],
                Vec::new(),
                Some("2022-11-03"),
            )],
            Vec::new(),
            Vec::new(),
            Some("php"),
        ),
        entry(
            "php-8.0",
            "PHP 8.0",
            "PHP-FPM 8.0 runtime with the common CMS extensions.",
            "PHP 8.0 introduced the JIT and named arguments. Suitable for CMS deployments that target this line.",
            Category::Runtime,
            EntryKind::System,
            &["php", "runtime", "fpm", "jit"],
            "PHP-3.01",
            "PHP Group",
            "https://www.php.net",
            vec![version(
                "8.0.30",
                mib(96),
                None,
                vec![
                    "php8.0-fpm",
                    "php8.0-cli",
                    "php8.0-curl",
                    "php8.0-gd",
                    "php8.0-intl",
                    "php8.0-mbstring",
                    "php8.0-mysql",
                    "php8.0-xml",
                    "php8.0-zip",
                ],
                Vec::new(),
                Some("2023-11-07"),
            )],
            Vec::new(),
            Vec::new(),
            Some("php"),
        ),
        entry(
            "php-8.1",
            "PHP 8.1",
            "PHP-FPM 8.1 runtime with the common CMS extensions.",
            "PHP 8.1 added enums, fibers, and read-only properties. Recommended baseline for new CMS deployments.",
            Category::Runtime,
            EntryKind::System,
            &["php", "runtime", "fpm"],
            "PHP-3.01",
            "PHP Group",
            "https://www.php.net",
            vec![version(
                "8.1.28",
                mib(108),
                None,
                vec![
                    "php8.1-fpm",
                    "php8.1-cli",
                    "php8.1-curl",
                    "php8.1-gd",
                    "php8.1-intl",
                    "php8.1-mbstring",
                    "php8.1-mysql",
                    "php8.1-xml",
                    "php8.1-zip",
                ],
                Vec::new(),
                Some("2024-04-11"),
            )],
            Vec::new(),
            Vec::new(),
            Some("php"),
        ),
        entry(
            "php-8.2",
            "PHP 8.2",
            "PHP-FPM 8.2 runtime with the common CMS extensions.",
            "PHP 8.2 introduced readonly classes and standalone types.",
            Category::Runtime,
            EntryKind::System,
            &["php", "runtime", "fpm"],
            "PHP-3.01",
            "PHP Group",
            "https://www.php.net",
            vec![version(
                "8.2.18",
                mib(112),
                None,
                vec![
                    "php8.2-fpm",
                    "php8.2-cli",
                    "php8.2-curl",
                    "php8.2-gd",
                    "php8.2-intl",
                    "php8.2-mbstring",
                    "php8.2-mysql",
                    "php8.2-xml",
                    "php8.2-zip",
                ],
                Vec::new(),
                Some("2024-04-11"),
            )],
            Vec::new(),
            Vec::new(),
            Some("php"),
        ),
        entry(
            "php-8.3",
            "PHP 8.3",
            "PHP-FPM 8.3 runtime with the common CMS extensions.",
            "PHP 8.3 is the current stable line and the panel's default for new sites.",
            Category::Runtime,
            EntryKind::System,
            &["php", "runtime", "fpm", "default"],
            "PHP-3.01",
            "PHP Group",
            "https://www.php.net",
            vec![version(
                "8.3.6",
                mib(118),
                None,
                vec![
                    "php8.3-fpm",
                    "php8.3-cli",
                    "php8.3-curl",
                    "php8.3-gd",
                    "php8.3-intl",
                    "php8.3-mbstring",
                    "php8.3-mysql",
                    "php8.3-xml",
                    "php8.3-zip",
                ],
                Vec::new(),
                Some("2024-04-11"),
            )],
            Vec::new(),
            Vec::new(),
            Some("php"),
        ),
        // =============== Databases ===============
        entry(
            "mysql",
            "MySQL 8.0",
            "The world's most popular open-source relational database.",
            "MySQL 8.0 is the production-grade default for OpenPanel sites. The recipe installs the distro package, initializes the data directory, and registers the service.",
            Category::Database,
            EntryKind::System,
            &["database", "sql", "relational"],
            "GPL-2.0-only",
            "Oracle Corporation",
            "https://www.mysql.com",
            vec![version(
                "8.0.36",
                mib(190),
                None,
                vec!["mysql-server"],
                Vec::new(),
                Some("2024-04-30"),
            )],
            Vec::new(),
            vec!["mariadb"],
            Some("mysql"),
        ),
        entry(
            "mysql-5.7",
            "MySQL 5.7",
            "Legacy MySQL line for applications that have not migrated.",
            "MySQL 5.7 reached end of life in 2023. Use only when an application is incompatible with 8.0.",
            Category::Database,
            EntryKind::System,
            &["database", "sql", "relational", "legacy"],
            "GPL-2.0-only",
            "Oracle Corporation",
            "https://www.mysql.com",
            vec![version(
                "5.7.44",
                mib(160),
                None,
                vec!["mysql-server-5.7"],
                Vec::new(),
                Some("2023-10-25"),
            )],
            Vec::new(),
            vec!["mysql", "mariadb"],
            Some("mysql"),
        ),
        entry(
            "mariadb",
            "MariaDB 10.11",
            "Drop-in MySQL replacement with a fully open-source governance model.",
            "MariaDB is a community-developed fork of MySQL with a strict open-source license. The panel supports either MySQL or MariaDB, never both.",
            Category::Database,
            EntryKind::System,
            &["database", "sql", "relational"],
            "GPL-2.0-only",
            "MariaDB Foundation",
            "https://mariadb.org",
            vec![version(
                "10.11.6",
                mib(180),
                None,
                vec!["mariadb-server"],
                Vec::new(),
                Some("2024-05-09"),
            )],
            Vec::new(),
            vec!["mysql", "mysql-5.7"],
            Some("mariadb"),
        ),
        entry(
            "postgresql",
            "PostgreSQL 16",
            "Advanced open-source relational database with strong SQL and JSON support.",
            "PostgreSQL is the most advanced open-source relational database. The recipe installs the distro package and registers the service.",
            Category::Database,
            EntryKind::System,
            &["database", "sql", "relational", "json"],
            "PostgreSQL",
            "PostgreSQL Global Development Group",
            "https://www.postgresql.org",
            vec![version(
                "16.3",
                mib(220),
                None,
                vec!["postgresql"],
                Vec::new(),
                Some("2024-05-09"),
            )],
            Vec::new(),
            Vec::new(),
            Some("postgresql"),
        ),
        // =============== Caches ===============
        entry(
            "redis",
            "Redis 7",
            "In-memory data structure store used for caching, sessions, and queues.",
            "Redis is the panel's default object cache. The recipe installs the distro package, enables the systemd service, and exposes a `redis-cli ping` readiness probe.",
            Category::Cache,
            EntryKind::System,
            &["cache", "kv", "memory"],
            "RSALv2",
            "Redis Ltd.",
            "https://redis.io",
            vec![version(
                "7.2.4",
                mib(7),
                None,
                vec!["redis-server"],
                Vec::new(),
                Some("2024-04-16"),
            )],
            Vec::new(),
            Vec::new(),
            Some("redis"),
        ),
        entry(
            "memcached",
            "Memcached 1.6",
            "High-performance distributed memory object caching system.",
            "Memcached is an alternative object cache. Use Redis unless a specific application requires Memcached.",
            Category::Cache,
            EntryKind::System,
            &["cache", "kv", "memory"],
            "BSD-3-Clause",
            "Danga Interactive",
            "https://memcached.org",
            vec![version(
                "1.6.27",
                mib(4),
                None,
                vec!["memcached"],
                Vec::new(),
                Some("2024-04-15"),
            )],
            Vec::new(),
            Vec::new(),
            Some("memcached"),
        ),
        // =============== Tools ===============
        entry(
            "phpmyadmin",
            "phpMyAdmin 5",
            "Web-based MySQL and MariaDB administration tool.",
            "phpMyAdmin is the de-facto MySQL administration UI. The recipe deploys it as a panel-managed site at `/pma` of the chosen domain.",
            Category::Tools,
            EntryKind::Web,
            &["database", "admin", "mysql"],
            "GPL-2.0-only",
            "phpMyAdmin contributors",
            "https://www.phpmyadmin.net",
            vec![version(
                "5.2.2",
                mib(22),
                Some(artifact(
                    "https://files.phpmyadmin.net/phpMyAdmin/5.2.2/phpMyAdmin-5.2.2-all-languages.tar.gz",
                    // Placeholder digest; the live fetcher verifies against the
                    // upstream hashcat and fails closed if it changes.
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "phpMyAdmin-5.2.2-all-languages",
                    None,
                )),
                Vec::new(),
                vec!["7.4", "8.0", "8.1", "8.2", "8.3"],
                Some("2024-04-15"),
            )],
            vec!["php-8.1"],
            Vec::new(),
            Some("phpmyadmin"),
        ),
        entry(
            "adminer",
            "Adminer 4",
            "Single-file database administration in PHP.",
            "Adminer is a lightweight alternative to phpMyAdmin, distributed as a single PHP file. The recipe deploys it as a panel-managed site at `/adminer` of the chosen domain.",
            Category::Tools,
            EntryKind::Web,
            &["database", "admin", "mysql", "lightweight"],
            "Apache-2.0",
            "Jakub Vrána",
            "https://www.adminer.org",
            vec![version(
                "4.8.1",
                mib(2),
                Some(file_artifact(
                    "https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-en.php",
                    // Placeholder digest; the live fetcher skips the
                    // digest check for documented placeholders.
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "adminer-4.8.1-en.php",
                )),
                Vec::new(),
                vec!["7.4", "8.0", "8.1", "8.2", "8.3"],
                Some("2023-01-19"),
            )],
            vec!["php-8.1"],
            Vec::new(),
            Some("adminer"),
        ),
        // =============== One-click apps ===============
        entry(
            "wordpress",
            "WordPress",
            "The world's most popular content management system.",
            "WordPress powers a large fraction of the public web. The recipe deploys the latest release to a new site, creates a dedicated database, and returns administrator credentials once.",
            Category::OneClick,
            EntryKind::Web,
            &["cms", "blog", "php", "mysql"],
            "GPL-2.0-or-later",
            "WordPress Foundation",
            "https://wordpress.org",
            vec![
                version(
                    "6.5.2",
                    mib(34),
                    Some(artifact(
                        "https://wordpress.org/wordpress-6.5.2.tar.gz",
                        "0000000000000000000000000000000000000000000000000000000000000000",
                        "wordpress",
                        Some("0000000000000000000000000000000000000000"),
                    )),
                    Vec::new(),
                    vec!["7.4", "8.0", "8.1", "8.2", "8.3"],
                    Some("2024-04-09"),
                ),
                version(
                    "6.4.3",
                    mib(34),
                    Some(artifact(
                        "https://wordpress.org/wordpress-6.4.3.tar.gz",
                        "0000000000000000000000000000000000000000000000000000000000000000",
                        "wordpress",
                        Some("0000000000000000000000000000000000000000"),
                    )),
                    Vec::new(),
                    vec!["7.4", "8.0", "8.1", "8.2", "8.3"],
                    Some("2024-03-05"),
                ),
            ],
            vec!["php-8.1", "mysql"],
            Vec::new(),
            Some("wordpress"),
        ),
        entry(
            "drupal",
            "Drupal",
            "Enterprise content management framework with strong content-modelling tools.",
            "Drupal is a PHP application framework with a content-management focus. The recipe deploys the latest release to a new site and provisions a dedicated database.",
            Category::OneClick,
            EntryKind::Web,
            &["cms", "framework", "php", "mysql"],
            "GPL-2.0-or-later",
            "Drupal Association",
            "https://www.drupal.org",
            vec![version(
                "10.3.0",
                mib(48),
                Some(artifact(
                    "https://ftp.drupal.org/files/projects/drupal-10.3.0.tar.gz",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "drupal-10.3.0",
                    None,
                )),
                Vec::new(),
                vec!["8.1", "8.2", "8.3"],
                Some("2024-04-17"),
            )],
            vec!["php-8.2", "mysql"],
            Vec::new(),
            Some("drupal"),
        ),
        entry(
            "joomla",
            "Joomla 5",
            "Mature content management system with strong multilingual support.",
            "Joomla 5 is the current major release line and the first to drop legacy PHP support. The recipe deploys Joomla 5 to a new site and provisions a database.",
            Category::OneClick,
            EntryKind::Web,
            &["cms", "multilingual", "php", "mysql"],
            "GPL-2.0-or-later",
            "Open Source Matters",
            "https://www.joomla.org",
            vec![version(
                "5.1.0",
                mib(40),
                Some(artifact(
                    "https://github.com/joomla/joomla-cms/releases/download/5.1.0/Joomla_5.1.0-Stable-Full_Package.tar.gz",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "Joomla_5.1.0-Stable-Full_Package",
                    None,
                )),
                Vec::new(),
                vec!["8.1", "8.2", "8.3"],
                Some("2024-04-16"),
            )],
            vec!["php-8.1", "mysql"],
            Vec::new(),
            Some("joomla"),
        ),
        entry(
            "ghost",
            "Ghost 5",
            "Modern publishing platform built on Node.js for professional bloggers.",
            "Ghost is a publishing-focused Node.js application. The recipe deploys Ghost and provisions a dedicated database.",
            Category::OneClick,
            EntryKind::Web,
            &["cms", "blog", "node"],
            "MIT",
            "Ghost Foundation",
            "https://ghost.org",
            vec![version(
                "5.85.0",
                mib(48),
                Some(artifact(
                    "https://github.com/TryGhost/Ghost/releases/download/v5.85.0/ghost-5.85.0.zip",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "ghost-5.85.0",
                    None,
                )),
                Vec::new(),
                Vec::new(),
                Some("2024-04-17"),
            )],
            vec!["mysql"],
            Vec::new(),
            Some("ghost"),
        ),
        entry(
            "typecho",
            "Typecho",
            "Lightweight PHP blogging platform with a small footprint.",
            "Typecho is a minimal PHP blog engine aimed at writers who value a clean, fast interface.",
            Category::OneClick,
            EntryKind::Web,
            &["cms", "blog", "php", "lightweight"],
            "GPL-2.0-only",
            "Typecho team",
            "https://typecho.org",
            vec![version(
                "1.2.1",
                mib(4),
                Some(artifact(
                    "https://github.com/typecho/typecho/releases/download/v1.2.1/typecho.v1.2.1.tar.gz",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "build",
                    None,
                )),
                Vec::new(),
                vec!["7.4", "8.0", "8.1", "8.2", "8.3"],
                Some("2023-04-15"),
            )],
            vec!["php-8.1", "mysql"],
            Vec::new(),
            Some("typecho"),
        ),
        entry(
            "nextcloud",
            "Nextcloud Hub",
            "Self-hosted file sync, sharing, and collaboration platform.",
            "Nextcloud is a self-hosted productivity suite. The recipe deploys the latest stable release to a new site, provisions a database, and configures trusted domains.",
            Category::OneClick,
            EntryKind::Web,
            &["collaboration", "files", "sync", "php"],
            "AGPL-3.0-only",
            "Nextcloud GmbH",
            "https://nextcloud.com",
            vec![version(
                "29.0.1",
                mib(180),
                Some(artifact(
                    "https://download.nextcloud.com/server/releases/nextcloud-29.0.1.tar.bz2",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "nextcloud",
                    None,
                )),
                Vec::new(),
                vec!["8.1", "8.2", "8.3"],
                Some("2024-05-02"),
            )],
            vec!["php-8.2", "mysql"],
            Vec::new(),
            Some("nextcloud"),
        ),
        entry(
            "matomo",
            "Matomo",
            "Privacy-focused web analytics platform you self-host.",
            "Matomo is a self-hosted analytics platform that does not share data with third parties. The recipe deploys Matomo to a new site and provisions a database.",
            Category::OneClick,
            EntryKind::Web,
            &["analytics", "privacy", "php", "mysql"],
            "GPL-3.0-or-later",
            "Matomo team",
            "https://matomo.org",
            vec![version(
                "5.0.3",
                mib(40),
                Some(artifact(
                    "https://builds.matomo.org/matomo-5.0.3.tar.gz",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "matomo",
                    None,
                )),
                Vec::new(),
                vec!["8.1", "8.2", "8.3"],
                Some("2024-04-29"),
            )],
            vec!["php-8.1", "mysql"],
            Vec::new(),
            Some("matomo"),
        ),
        entry(
            "bookstack",
            "BookStack",
            "Simple, self-hosted wiki and documentation platform.",
            "BookStack is a wiki-style documentation platform. The recipe deploys BookStack and provisions a database.",
            Category::OneClick,
            EntryKind::Web,
            &["wiki", "docs", "php", "mysql"],
            "MIT",
            "BookStack project",
            "https://www.bookstackapp.com",
            vec![version(
                "24.04",
                mib(40),
                Some(artifact(
                    "https://github.com/BookStackApp/BookStack/releases/download/v24.04/BookStack-v24.04.zip",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "BookStack-v24.04",
                    None,
                )),
                Vec::new(),
                vec!["8.1", "8.2", "8.3"],
                Some("2024-04-22"),
            )],
            vec!["php-8.1", "mysql"],
            Vec::new(),
            Some("bookstack"),
        ),
        entry(
            "halo",
            "Halo",
            "Modern, extensible content management system written in Java.",
            "Halo is a modern CMS written in Java. The recipe deploys Halo to a new site.",
            Category::OneClick,
            EntryKind::Web,
            &["cms", "java", "blog"],
            "GPL-3.0-or-later",
            "Halo team",
            "https://halo.run",
            vec![version(
                "2.18.0",
                mib(220),
                Some(artifact(
                    "https://github.com/halo-dev/halo/releases/download/v2.18.0/halo-2.18.0.jar",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "halo-2.18.0",
                    None,
                )),
                Vec::new(),
                Vec::new(),
                Some("2024-05-09"),
            )],
            Vec::new(),
            Vec::new(),
            Some("halo"),
        ),
        entry(
            "discourse",
            "Discourse",
            "Modern forum and community platform.",
            "Discourse is the modern forum platform powering many open-source communities. The recipe provisions a dedicated site and a PostgreSQL database.",
            Category::OneClick,
            EntryKind::Web,
            &["forum", "community", "ruby"],
            "GPL-2.0-only",
            "Civilized Discourse Construction Kit, Inc.",
            "https://www.discourse.org",
            vec![version(
                "3.2.2",
                mib(160),
                Some(artifact(
                    "https://github.com/discourse/discourse/releases/download/v3.2.2/discourse-3.2.2.zip",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "discourse-3.2.2",
                    None,
                )),
                Vec::new(),
                Vec::new(),
                Some("2024-05-09"),
            )],
            vec!["postgresql"],
            Vec::new(),
            Some("discourse"),
        ),
        entry(
            "gitea",
            "Gitea",
            "Lightweight self-hosted Git service.",
            "Gitea is a self-hosted Git service with a clean, fast interface. The recipe deploys Gitea to a new site and provisions a database.",
            Category::OneClick,
            EntryKind::Web,
            &["git", "dev", "go"],
            "MIT",
            "Gitea project",
            "https://gitea.io",
            vec![version(
                "1.22.0",
                mib(80),
                Some(artifact(
                    "https://github.com/go-gitea/gitea/releases/download/v1.22.0/gitea-1.22.0-linux-amd64",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "gitea-1.22.0",
                    None,
                )),
                Vec::new(),
                Vec::new(),
                Some("2024-05-07"),
            )],
            vec!["mysql"],
            Vec::new(),
            Some("gitea"),
        ),
        entry(
            "mattermost",
            "Mattermost",
            "Self-hosted Slack alternative for team messaging.",
            "Mattermost is a self-hosted team messaging platform. The recipe deploys Mattermost to a new site and provisions a database.",
            Category::OneClick,
            EntryKind::Web,
            &["chat", "team", "go"],
            "MIT",
            "Mattermost, Inc.",
            "https://mattermost.com",
            vec![version(
                "9.7.0",
                mib(120),
                Some(artifact(
                    "https://github.com/mattermost/mattermost/releases/download/v9.7.0/mattermost-9.7.0-linux-amd64.tar.gz",
                    "0000000000000000000000000000000000000000000000000000000000000000",
                    "mattermost",
                    None,
                )),
                Vec::new(),
                Vec::new(),
                Some("2024-05-09"),
            )],
            vec!["mysql"],
            Vec::new(),
            Some("mattermost"),
        ),
        // =============== Security ===============
        entry(
            "fail2ban",
            "Fail2ban",
            "Bans IPs that show malicious signs by monitoring service logs.",
            "Fail2ban scans log files and bans IPs that show malicious activity. The recipe installs the distro package and enables the SSH and panel jails.",
            Category::Security,
            EntryKind::System,
            &["security", "ssh", "intrusion"],
            "GPL-2.0-only",
            "Fail2ban contributors",
            "https://github.com/fail2ban/fail2ban",
            vec![version(
                "1.1.0",
                mib(4),
                None,
                vec!["fail2ban"],
                Vec::new(),
                Some("2024-04-20"),
            )],
            Vec::new(),
            Vec::new(),
            Some("fail2ban"),
        ),
    ]
}

/// Build the embedded manifest. Used by the embedded source and by the
/// service on first boot when no remote manifest has ever been activated.
pub fn embedded_manifest() -> Result<CatalogManifest, super::SoftwareCenterError> {
    let manifest = CatalogManifest {
        schema: 1,
        issued_at: "2024-05-10T00:00:00Z".to_owned(),
        source_url: "https://catalog.openpanel.invalid/v1/manifest.json".to_owned(),
        entries: entries(),
    };
    manifest
        .validate()
        .map_err(|_| super::SoftwareCenterError::Invalid("seed entry invalid".into()))?;
    Ok(manifest)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seed_manifest_validates() {
        let manifest = embedded_manifest().expect("seed manifest must validate");
        assert!(manifest.entries.len() >= 25);
    }

    #[test]
    fn php_runtimes_are_mutually_unique() {
        let ids: Vec<_> = entries().into_iter().map(|entry| entry.id).collect();
        let unique: std::collections::BTreeSet<_> = ids.iter().collect();
        assert_eq!(unique.len(), ids.len());
    }
}
