CREATE TABLE IF NOT EXISTS mail_domains(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,name TEXT NOT NULL UNIQUE,enabled INTEGER NOT NULL,quota_bytes INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS mail_mailboxes(id TEXT PRIMARY KEY,domain_id TEXT NOT NULL REFERENCES mail_domains(id) ON DELETE CASCADE,address TEXT NOT NULL UNIQUE,quota_bytes INTEGER NOT NULL,enabled INTEGER NOT NULL,password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mail_aliases(id TEXT PRIMARY KEY,domain_id TEXT NOT NULL REFERENCES mail_domains(id) ON DELETE CASCADE,source TEXT NOT NULL UNIQUE,destination TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS mail_dkim(domain_id TEXT PRIMARY KEY REFERENCES mail_domains(id) ON DELETE CASCADE,selector TEXT NOT NULL,encrypted_private_key TEXT NOT NULL,public_value TEXT NOT NULL);
